### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by rezaAdinepour** [Theborna/latex-uni-document#1]
How can change this template to the Farsi?

**Comment by rezaAdinepour** [comment]
if we can't change this, please upload another repo for Farsi document.
Thanks Borna

**Comment by Theborna** [comment]
hey, you can change the language to Farsi as well. like the following

\usepackage[bordered]{uni-style} %\usepackage[bordered, en]{uni-style} for english

![code](https://github.com/Theborna/latex-uni-document/assets/38924779/7a7ec7bb-c3a1-4c8a-b09b-43b9aa48e756)

here i have also included a .zip file of a Farsi project i have done using this template.

[PS7.zip](https://github.com/Theborna/latex-uni-document/files/12658375/PS7.zip)

**Comment by rezaAdinepour** [comment]
Thanks a lot Borna
